server:
  port: 8088

logging:
  level:
    org.springframework: debug

spring:
  messages:
    basename: messages
#  security:
#    user:
#      name: username
#      password: passw0rd
#    springboot 2.7 에서 springfox 를 위한 설정
#    mvc:
#      pathmatch:
#        matching-stragegy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
        #* 은 모든 것을 다 오픈한 상태 = 보안성 취약

